# TCL File Generated by Component Editor 18.1
# Mon Apr 26 07:43:54 CEST 2021
# DO NOT MODIFY


# 
# accelerator "accelerator" v1.0
#  2021.04.26.07:43:54
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module accelerator
# 
set_module_property DESCRIPTION ""
set_module_property NAME accelerator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME accelerator
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL accelerator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file reverse_hw.vhd VHDL PATH ../hdl/reverse_hw.vhd
add_fileset_file accelerator.vhd VHDL PATH ../hdl/accelerator/accelerator.vhd TOP_LEVEL_FILE
add_fileset_file dma.vhd VHDL PATH ../hdl/accelerator/dma.vhd
add_fileset_file op_handler.vhd VHDL PATH ../hdl/accelerator/op_handler.vhd
add_fileset_file registers.vhd VHDL PATH ../hdl/accelerator/registers.vhd
add_fileset_file fifo.vhd VHDL PATH ../hdl/accelerator/fifo/fifo.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point as
# 
add_interface as avalon end
set_interface_property as addressUnits WORDS
set_interface_property as associatedClock clock
set_interface_property as associatedReset reset_sink
set_interface_property as bitsPerSymbol 8
set_interface_property as burstOnBurstBoundariesOnly false
set_interface_property as burstcountUnits WORDS
set_interface_property as explicitAddressSpan 0
set_interface_property as holdTime 0
set_interface_property as linewrapBursts false
set_interface_property as maximumPendingReadTransactions 0
set_interface_property as maximumPendingWriteTransactions 0
set_interface_property as readLatency 0
set_interface_property as readWaitTime 1
set_interface_property as setupTime 0
set_interface_property as timingUnits Cycles
set_interface_property as writeWaitTime 0
set_interface_property as ENABLED true
set_interface_property as EXPORT_OF ""
set_interface_property as PORT_NAME_MAP ""
set_interface_property as CMSIS_SVD_VARIABLES ""
set_interface_property as SVD_ADDRESS_GROUP ""

add_interface_port as AS_address address Input 2
add_interface_port as AS_read read Input 1
add_interface_port as AS_readdata readdata Output 32
add_interface_port as AS_write write Input 1
add_interface_port as AS_writedata writedata Input 32
set_interface_assignment as embeddedsw.configuration.isFlash 0
set_interface_assignment as embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment as embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment as embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink nReset reset_n Input 1


# 
# connection point am
# 
add_interface am avalon start
set_interface_property am addressUnits SYMBOLS
set_interface_property am associatedClock clock
set_interface_property am associatedReset reset_sink
set_interface_property am bitsPerSymbol 8
set_interface_property am burstOnBurstBoundariesOnly false
set_interface_property am burstcountUnits WORDS
set_interface_property am doStreamReads false
set_interface_property am doStreamWrites false
set_interface_property am holdTime 0
set_interface_property am linewrapBursts false
set_interface_property am maximumPendingReadTransactions 0
set_interface_property am maximumPendingWriteTransactions 0
set_interface_property am readLatency 0
set_interface_property am readWaitTime 1
set_interface_property am setupTime 0
set_interface_property am timingUnits Cycles
set_interface_property am writeWaitTime 0
set_interface_property am ENABLED true
set_interface_property am EXPORT_OF ""
set_interface_property am PORT_NAME_MAP ""
set_interface_property am CMSIS_SVD_VARIABLES ""
set_interface_property am SVD_ADDRESS_GROUP ""

add_interface_port am AM_address address Output 32
add_interface_port am AM_burstcount burstcount Output 5
add_interface_port am AM_read read Output 1
add_interface_port am AM_readdata readdata Input 32
add_interface_port am AM_readdatavalid readdatavalid Input 1
add_interface_port am AM_write write Output 1
add_interface_port am AM_writedata writedata Output 32
add_interface_port am AM_waitrequest waitrequest Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint as
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1

